DATA_ROOT: "/data/ephemeral/home/level2-cv-semanticsegmentation-cv-13/data"
SAVED_DIR: "/data/ephemeral/home/level2-cv-semanticsegmentation-cv-13/model"
EXP_NAME: "temp"
CAMPER_ID: "T0000"
BATCH_SIZE: 8
LR: 0.0001
RANDOM_SEED: 21
NUM_EPOCHS: 50
VAL_EVERY: 5