DATA_ROOT: "/data/ephemeral/home/level2-cv-semanticsegmentation-cv-13/data"
SAVED_DIR: "/data/ephemeral/home/level2-cv-semanticsegmentation-cv-13/model"
EXP_NAME: "temp"
CAMPER_ID: "T0000"
BATCH_SIZE: 8
LR: 0.0001
RANDOM_SEED: 21
NUM_EPOCHS: 50
VAL_EVERY: 5
RESIZE: 512

PSEUDO_LABEL: False
OUTPUT_CSV_PATH: "/data/ephemeral/home/level2-cv-semanticsegmentation-cv-13/result/output.csv"

loss:
  name: "cross_entropy"
  params: null

# torchvision or smp
TYPE: torchvision
# torchvision: fcn, deeplab
# smp: Unet, UnetPlusPlus, MAnet, Linknet, FPN, PSPNet, DeepLabV3, DeepLabV3Plus, PAN
MODEL: fcn
# https://github.com/qubvel/segmentation_models.pytorch?tab=readme-ov-file#encoders
ENCODER: null
